# Assignment #01

This assignment is composed of multiple Python and NumPy programming exercises. The deliverable of this assignment is this jupyter-notebook completed with your solution.

The delivery instructions are the following:
    - Create a GitHub repository for your team. You are free to choose its name. This repository will be used to delvier the programming assignments and the code of your team's final project.
    - Create a folder assignment-01 in the repository. Put the jupyter-notebook with your solution in this repository and post the repository link in your team's D2L dropbox for the assignment.

You are being assessed based on:

1. Code execution - 25% 
2. Clarity of the code (e.g., easy to follow, has pertinent comments, etc.) - 25%
3. Proper usage of the techniques seen in class - 25%
    - remember to avoid explicit Python loops!  
4. Quality and correcteness of the results - 25%

More details about the assessment are available in the rubric document in the class GitHub repository.

Points distribution:
- Question 2-21: 3 points per question 
- Questions 22-26: 8 points per question (total 40)
- Total: 100 ponits

In [1]:
import matplotlib.pylab as plt

**1. Import the numpy package under the name np**

In [102]:
import numpy as np

**2. Print the numpy version and the configuration**

In [101]:
# version
print(np.__version__)

# config
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/guojun/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/guojun/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/guojun/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/guojun/anaconda3/include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/guojun/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/guojun/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/guojun/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/guojun/anaconda3/include']
Supported SIMD extensions in 

**3. Create a 1D array of zeros of size 10 of type float32**

In [100]:
# a = np.array([0] * 10, dtype=np.float32)
a = np.zeros(10, dtype=np.float32)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4. Print the memory size of the array below**

In [99]:
Z = np.zeros((32,12))
# Include your solution below
print(f"Total size: {Z.nbytes} bytes")

Total size: 3072 bytes


**5. Create a 1D array with values ranging from 10 to 58**

In [98]:
# b = np.array([x for x in range(10, 58)])
b = np.arange(10, 58)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57]


**6. Reverse the order of the values in the vector (first element becomes last)**

In [97]:
a = np.arange(10)
# Include your solution below
a = np.flip(a)
print(a)

[9 8 7 6 5 4 3 2 1 0]


**7. Create a 3x3 matrix with values ranging from 0 to 8**

In [96]:
# ranging from 0 to 8
a = np.arange(9)
# reshaping to 3x3
a = a.reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**8. Create a 3x3 identity matrix**

In [95]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**9. Find and print the maximum values of each column in the array below** 

In [94]:
Z = np.random.random((10,11))
# Include your solution below
print(Z.max(axis=0))

[0.93551292 0.97130738 0.94729968 0.97076076 0.93397609 0.98446798
 0.92934139 0.9840386  0.79281604 0.49078841 0.98129925]


**10. Create a $7 \times 7$ array with 1s on the borders (first row and column, last row and columns) and 0s everywhere else**

In [93]:
# create a 7 * 7 matrix with 1s
a = np.ones((7, 7))
    # fill the 0s to the non-border elements
a[1:-1, 1:-1].fill(0)
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


**11. Pad the existing array below with zeros (i.e., add additional rows and columns with zeros). Use the NumPy pad function.**

In [92]:
Z = np.ones((5,5))
# Include your solution below
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**12. Extract the integer part of the random array of positive numbers below**

In [91]:
Z = np.random.uniform(0,10,10)
# Include your solution below
# integer part = number - decimal part (Z % 1)
print(Z - Z % 1)

[9. 6. 4. 3. 3. 0. 1. 2. 3. 7.]


**13. Create a 5x5 matrix with rows with equal values ranging from 0 to 4 (i.e., [0,1,2,3,4])**

*Hint:* consider using NumPy broadcasting or the tile function*

In [90]:
a = np.broadcast_to(np.arange(5), (5, 5))
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


**14. Create a vector of size 10 with values ranging from 0 to 1 (0 and 1 not included)**

*Hint: Consider using the linspace function*

In [89]:
# generate linear space size 11 and remove the first element
a = np.linspace(0, 1, 11, endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**15. Create a random vector of size 10 and sort it**

In [88]:
a = np.sort(np.random.random(10))
print(a)

[0.01370354 0.11700527 0.34986078 0.41119823 0.51011422 0.56787209
 0.68405146 0.68976388 0.71994233 0.76125173]


**16. Consider the cartesian coordinates below (X and Y), convert them to polar coordinates (R and T)**

In [86]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
# Include your solution below
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
a = np.column_stack((R, T))
print(a)


[[0.61151664 1.52280794]
 [0.98010969 0.22924757]
 [0.65561699 0.40739612]
 [0.30512972 0.56620396]
 [0.67700427 0.07144164]
 [0.66335824 0.75102278]
 [0.42218147 1.49834893]
 [1.15968524 0.88363966]
 [0.9224018  0.47418325]
 [0.45901706 0.29266483]]


**17. Create random vector of size 10 and replace the maximum value by 0**

In [75]:
a = np.random.random(10)
# find the max value's index
max_index = np.argmax(a)
# set to be 0
a[max_index] = 0
print(a) 

[0.7034934  0.28054337 0.1036611  0.41034182 0.62754302 0.02782593
 0.         0.71203319 0.04552242 0.52479044]


**18. Find the nearest value from a given value (z) in an array (Z)**

In [73]:
Z = np.random.uniform(0,1,10)
z = 0.5
# Include your solution below
# find the index of the closest value to z
min_abs_index = np.abs(Z - z).argmin()
z = Z[min_abs_index]
print(z)
print(Z)

0.5060694972420947
[0.53778067 0.60635589 0.85925602 0.45726267 0.5060695  0.98455007
 0.1414555  0.08656363 0.99027811 0.84569038]


**19. Consider the vector [5, 4, 3, 2, 1], how to build a new vector with 3 consecutive zeros interleaved between each value?**

In [71]:
Z = np.arange(5)[::-1]
# Include your solution below
# create a 5*5 matrix with 0s
a = np.zeros((5, 5))
# stack the 0s matrix to Z
Z = np.vstack((Z, a))
# flatten it to 1D array in column-major order
Z = Z.flatten(order='F')
print(Z)


[4. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


**20. Consider an array of dimension (5,5,3), how to mulitply it element-wise by an array with dimensions (5,5) - i.e., (5,5,0)$\times$(5,5), (5,5,1)$\times$(5,5), (5,5,2)$\times$(5,5)**

In [70]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
# Include your solution below
# increase the dimension by np.newaixs
print(np.multiply(A, B [:, :, np.newaxis]))


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


**21. Swap the first and second rows of the 2D array below**

In [69]:
W = np.arange(30).reshape(6,5)
print(W)
# Include your solution below
# assign row 0 to row 1 and row 1 to row 0
W[[0, 1]] = W[[1, 0]]
print(W)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


**22. Write a function that receives as input a 2D Boolean NumPy array and outputs the coordinates of the minimal bounding-box
that encloses all non-zero elements in the input array**

**Tip:** search for the functions nonzero and where in the NumPy documentation.


<img src="./bbox.png" width="150" /> 

In [68]:
def bbox(img):
    #include your solution below
    # return the non-zero element's index
    r, c = np.nonzero(img)
    # left-top point should be the min value of row and column
    # right-bottom point should be the max value of row and column
    r1, r2 = r.min(), r.max()
    c1, c2 = c.min(), c.max()
    return (r1,c1),(r2,c2)


from PIL import Image

img = np.array(Image.open('./bin_image.png').convert('L')) > 0
print(bbox(img))

((29, 50), (342, 431))


**23.Write a function to compute the average over a sliding window of length N over a 1D array?**

*Example:* [1,2,3,4,5,6,7,8,9], N = 3 -> [2,5,8]

In [67]:
def moving_average(x,N = 3):
    #define your function here
    # reshape into N rows
    a = x.reshape(N, -1)
    return np.mean(a, axis=1)

a = np.arange(30)
N = 3
print(moving_average(a,N))

[ 4.5 14.5 24.5]


**24.  Given a sorted 1D array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?**

*Example:* C = [3,2,4] -> D = [0,0,0,1,1,2,2,2,2]

*Tip:* Consider using the NumPy repeat function

In [66]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)
# Include yoru solution here
a = np.repeat(np.arange(len(C)), C)
print(a)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


**25. Find the most frequent value in the array below?**

In [65]:
Z = np.random.randint(0,10,50)
# Include your solution below
# return the index of the max frequency
a = np.bincount(Z).argmax()
print(a)

0


**26. Write a function to return the n largest values of an array** 

In [63]:
def nlargest(a,n = 5):
    # Include your solution here
    # use argsort to get the index of the sorted array and then return the last n-th element
    b = a[np.argsort(a)[-n]]
    return b

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(nlargest(Z,n))    

9995
